#pragma config(Motor,  motor2,          rightRear,     tmotorVexIQ, openLoop, reversed)
#pragma config(Motor,  motor3,          leftRear,      tmotorVexIQ, openLoop)
#pragma config(Motor,  motor4,          rightFore,     tmotorVexIQ, openLoop, reversed)
#pragma config(Motor,  motor5,          leftFore,      tmotorVexIQ, openLoop)
#pragma config(Motor,  motor6,          flipper,       tmotorVexIQ, openLoop)

//*!!  Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This is just the basic code for the robot. More updates are to come.
// Last Updated: Sunday, January 13th, 2019


task main()
{
	while (true)
	{
		motor[rightRear] = vexRT[Ch2]; //Full power is 127
		motor[rightFore] = vexRT[Ch2]; //Full power is 127

		motor[leftRear] = vexRT[Ch3]; //Full power is 127
		motor[leftFore] = vexRT[Ch3]; //Full power is 127

		//motor[flipper] = vexRT[Ch6]; //Full power is 127
		
		//Arm Control
    if(vexRT[Btn6U] == 1)
    {
      motor[flipper] = 127;
    }
    else if(vexRT[Btn6D] == 1)
    {
      motor[flipper] = -127;
    }
    else
    {
      motor[flipper] = 0;
    }
	}
}
