#pragma config(Motor,  port2,           rightRear,     tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftRear,      tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port4,           rightFore,     tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           leftFore,      tmotorVex393TurboSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This is just the basic code for the robot. More updates are to come.
// Friday, January 11th, 2019


task main()
{
	while (true)
	{
		motor[rightRear] = vexRT[Ch2]/3; //Full power is 127
		motor[rightFore] = vexRT[Ch2]/3; //Full power is 127

		motor[leftRear] = vexRT[Ch3]/3; //Full power is 127
		motor[leftFore] = vexRT[Ch3]/3; //Full power is 127
	} 
}
