#pragma config(Motor,  port2,           rightRear,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port3,           leftRear,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port4,           rightFore,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port5,           leftFore,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port6,           flipper,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port7,           grabber,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This is just the basic code for the robot. More updates are to come.
// Last edited: Monday, January 14th, 2019


task main()
{
	while (true)
	{
		motor[rightRear] = vexRT[Ch2]; //Full power is 127
		motor[rightFore] = vexRT[Ch2]; //Full power is 127

		motor[leftRear] = vexRT[Ch3]; //Full power is 127
		motor[leftFore] = vexRT[Ch3]; //Full power is 127

		//motor[flipper] = vexRT[Ch6]; //Full power is 127
		
	

	//Flipper arm Control
    if(vexRT[Btn6U] == 1)
    {
      motor[flipper] = 127;
    }
    else if(vexRT[Btn6D] == 1)
    {
      motor[flipper] = -127;
    }//Hold motor arm control
    else if(vexRT[Btn5U] == 1)
    {
      motor[flipper] = 20;
    }
    else if(vexRT[Btn5D] == 1)
    {
      motor[flipper] = -20;
    }
    else
    {
      motor[flipper] = 0;
    }
    
    //Grabber arm control
    if(vexRT[Btn8U] == 1)
    {
      motor[grabber] = 127;
    } 
    else if(vexRT[Btn8D] == 1)
    {
    	motor[grabber] = -127;
    } 
    else
  	{
  		motor[grabber] = 0;	
  	}
   }
}
